[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://seu-backend-url.herokuapp.com" # Você precisará atualizar esta URL depois

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 