[build]
  command = "pip install -r backend/requirements.txt"
  publish = "backend"
  functions = "backend"

[build.environment]
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/main"
  status = 200

[functions]
  external_node_modules = [""]
  node_bundler = "esbuild" 